service:
  name: learn-serverless-ts
# app and org for use with dashboard.serverless.com
app: learn-serverless-ts-app
org: patrickmao93

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
